service: sample-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    events:
      - http:
          path: /get
          method: GET
  
  function2:
    handler: src/routes/login.finalHandler
    events:
      - http:
          path: /login
          method: GET

plugins:
  - serverless-offline